Neos:
  Neos:
    userInterface:
      backendLoginForm:
        backgroundImage: 'resource://IFSR.HomePage/Public/Images/LoginScreen.jpg'
    nodeTypes:
      groups:
        templates:
          position: 50
          label: 'Templates'
          collapsed: false
  Flow:
    mvc:
      routes:
        'IFSR.HomePage': true
  ContentRepository:
    contentDimensions:
      'language':
        label: 'Language'
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'en':
            label: 'English'
            values: ['en', 'de']
            uriSegment: 'en'
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
  Media:
    assetSources:
      unsplash:
        assetSource: 'DL\AssetSource\Unsplash\AssetSource\UnsplashAssetSource'
        assetSourceOptions:
          accessKey: 'aba2a6e9c424e57a1ce602148969bafad57f03c2c34aeaf6c94950d0bb9d4286'
          utmSource: 'Neos CMS Unsplash Asset Source https://neos.io'
